-- user password(12345) --
INSERT INTO my_light_blog.`user`(`name`, lastname, email, `password`) VALUES('root','root','root@localhost.com','5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5');
INSERT INTO my_light_blog.`user`(`name`, lastname, email, `password`) VALUES('username','userlastname','user@localhost.com','5994471abb01112afcc18159f6cc74b4f511b99806da59b3caf5a9c173cacfc5');

-- category --
INSERT INTO  my_light_blog.category(name) VALUES('developer');
INSERT INTO  my_light_blog.category(name) VALUES('javascript');
INSERT INTO  my_light_blog.category(name) VALUES('sql');
INSERT INTO  my_light_blog.category(name) VALUES('games');
INSERT INTO  my_light_blog.category(name) VALUES('Lorem Ipsum');

-- post  --
INSERT INTO  my_light_blog.post( title, body,`date`,`user`, category) VALUES('JavaScript isNaN() Function','Definition and Usage
																 The isNaN() function determines whether a value is an illegal number (Not-a-Number).
																 
																 This function returns true if the value equates to NaN. Otherwise it returns false.
																 
																 This function is different from the Number specific Number.isNaN() method.
																 
																 The global isNaN() function, converts the tested value to a Number, then tests it.
																 
																 Number.isNaN() does not convert the values to a Number, and will not return true for any value that is not of the type Number.','2018-08-20 15:49:00',1,2);


INSERT INTO  my_light_blog.post( title, body,`date`,`user`, category) VALUES('SQL INSERT INTO Statement','The INSERT INTO statement is used to insert new records in a table.
																INSERT INTO Syntax
																It is possible to write the INSERT INTO statement in two ways.

																The first way specifies both the column names and the values to be inserted.','2018-08-20 15:50:00',1,3);

INSERT INTO  my_light_blog.post( title, body,`date`,`user`, category) VALUES('Age of Empires III','TAge of Empires III is a real-time strategy video game developed by Microsoft Corporation\'s Ensemble Studios and published by Microsoft Game Studios. The Mac version was ported over and developed and published by Destineer\'s MacSoft. The PC version was released on October 18, 2005 in North America and November 4, 2005 in Europe, while the Mac version was released on November 21, 2006 in North America and September 29, 2006 in Europe. An N-Gage version of the game developed by Glu Mobile was released on April 28, 2009.[2][3][4] It is the third game of the Age of Empires series and the sequel to Age of Empires II: The Age of Kings.

																The game portrays the European colonization of the Americas, between approximately 1492 and 1876 AD. There are fourteen civilizations to play within the game. Age of Empires III has made several innovations in the series, in particular with the addition of the "Home City", which combines real-time strategy and role-playing features. Two expansion packs have been released: the first, Age of Empires III: The WarChiefs, was released on October 17, 2006, and introduced three Native American civilizations; the second, Age of Empires III: The Asian Dynasties, was released on October 23, 2007, and included three Asian civilizations.

																Age of Empires III has sold over 2 million copies as of May 2008. As well as receiving favorable reviews, it has garnered awards, including GameSpy','2018-08-20 15:55:30',1,4);
INSERT INTO  my_light_blog.post( title, body,`date`,`user`, category) VALUES('The SQL SELECT Statement','The SELECT statement is used to select data from a database.

																The data returned is stored in a result table, called the result-set.

																SELECT Syntax','2018-08-20 15:55:50',1,3);

INSERT INTO  my_light_blog.post( title, body,`date`,`user`, category) VALUES('How To Create a Login Form','The HTML <form> element defines a form that is used to collect user input:

 An HTML form contains form elements.

Form elements are different types of input elements, like text fields, checkboxes, radio buttons, submit buttons, and more.

The <input> Element
The <input> element is the most important form element.

The <input> element can be displayed in several ways, depending on the type attribute.','2018-08-20 15:58:20',1,1);

INSERT INTO  my_light_blog.post( title, body,`date`,`user`, category) VALUES('5 paragraphs of Lorem ipsum','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam malesuada quis nulla a facilisis. Etiam non tellus diam. Etiam sit amet lorem velit. Duis eros leo, dignissim vel aliquet sit amet, volutpat rutrum felis. Maecenas elementum, turpis eget elementum pulvinar, quam neque consectetur lectus, vitae posuere magna magna ut ligula. Nam tempus porttitor pharetra. Phasellus laoreet ante nec tellus lobortis pellentesque. Nullam non commodo dolor, sit amet dictum nunc.

Quisque iaculis pretium arcu, in pretium urna tincidunt a. Suspendisse potenti. Suspendisse potenti. Nunc varius massa vel ipsum interdum varius. Duis sed dapibus urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis consequat ex lorem, vitae tincidunt erat eleifend eget. Suspendisse consequat blandit volutpat. Curabitur dapibus, sem nec dignissim consectetur, magna ligula venenatis ex, maximus euismod arcu libero a augue.

Nam non aliquet odio, ut tincidunt felis. Sed est lectus, placerat sit amet enim sit amet, tempus dictum erat. Etiam tempus varius diam, a dictum libero euismod volutpat. Donec vitae ex in sem volutpat molestie ac ut orci. Cras id vulputate augue. Vestibulum sit amet mollis augue, at finibus dui. Vivamus mollis vulputate felis eu accumsan. Integer tincidunt, nulla eu interdum cursus, risus elit consequat dolor, vitae interdum purus magna nec lacus. Pellentesque fermentum est eget orci sagittis aliquet. Pellentesque ultrices nisl in nisi cursus tristique a vitae magna. Suspendisse aliquam est in ex suscipit laoreet. Maecenas quis luctus odio, eget rutrum nibh. Proin sodales hendrerit mauris ut efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse porta lacinia ante nec eleifend.

In facilisis sodales ligula, eu lacinia nibh ornare quis. Nam id varius justo. Donec elit ante, maximus id porta sit amet, pharetra ut nisi. Donec quis sapien in tortor faucibus blandit. Aenean tristique ligula at augue dictum luctus. Ut egestas gravida arcu nec condimentum. Pellentesque bibendum faucibus lacus, nec dignissim risus vehicula a. Curabitur eu hendrerit neque, eget suscipit est.

Etiam tincidunt, lorem non rhoncus aliquam, sem urna consequat felis, sed maximus turpis lectus in nibh. Phasellus lobortis, turpis eget cursus imperdiet, nisi libero consequat quam, in congue libero mauris ac tortor. Donec viverra iaculis ultricies. Vivamus eu justo quis elit vestibulum sagittis eu non leo. Nunc elementum mollis mauris. Nullam interdum malesuada augue, et sagittis arcu accumsan id. Nunc ac cursus sem. Nullam sodales nisl vitae commodo cursus. Nullam sed mauris quis est pellentesque convallis quis in odio. Fusce molestie sit amet neque eu facilisis.','2018-08-20 15:57:50',1,5);

INSERT INTO  my_light_blog.post( title, body,`date`,`user`, category) VALUES('20 paragraphs of Lorem ipsum',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras elementum. Suspendisse nisl. Nulla non arcu lacinia neque faucibus fringilla. Etiam neque. Aenean placerat. Integer in sapien. Maecenas lorem. Duis risus. Praesent id justo in neque elementum ultrices. Etiam posuere lacus quis dolor.

In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Praesent id justo in neque elementum ultrices. Suspendisse sagittis ultrices augue. Praesent dapibus. Pellentesque arcu. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Quisque porta. Aenean id metus id velit ullamcorper pulvinar. Fusce tellus. Etiam egestas wisi a erat. In convallis. Aenean placerat. Pellentesque sapien. Proin mattis lacinia justo. Praesent dapibus.

Aliquam in lorem sit amet leo accumsan lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Aenean id metus id velit ullamcorper pulvinar. Duis pulvinar. Nullam dapibus fermentum ipsum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Maecenas libero. Etiam dictum tincidunt diam. Nullam rhoncus aliquam metus. Aliquam erat volutpat. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Integer in sapien. Mauris tincidunt sem sed arcu. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui.

Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim. Fusce nibh. Aenean fermentum risus id tortor. Mauris elementum mauris vitae tortor. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Curabitur bibendum justo non orci. Integer vulputate sem a nibh rutrum consequat. Aenean placerat. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Mauris tincidunt sem sed arcu. Nulla est. Morbi scelerisque luctus velit. Curabitur bibendum justo non orci. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Ut tempus purus at lorem. Nunc tincidunt ante vitae massa. Donec iaculis gravida nulla.

Phasellus faucibus molestie nisl. Phasellus et lorem id felis nonummy placerat. Aliquam ante. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Aliquam in lorem sit amet leo accumsan lacinia. Et harum quidem rerum facilis est et expedita distinctio. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Integer tempor. Cras pede libero, dapibus nec, pretium sit amet, tempor quis. Aenean id metus id velit ullamcorper pulvinar. Quisque tincidunt scelerisque libero. Duis condimentum augue id magna semper rutrum. Integer in sapien. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Etiam dictum tincidunt diam.

Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. In rutrum. Nulla quis diam. Mauris elementum mauris vitae tortor. Nulla non lectus sed nisl molestie malesuada. Integer lacinia. Nunc tincidunt ante vitae massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede. Nunc tincidunt ante vitae massa. Mauris suscipit, ligula sit amet pharetra semper, nibh ante cursus purus, vel sagittis velit mauris vel metus. Duis risus. Vestibulum fermentum tortor id mi. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Nullam sit amet magna in magna gravida vehicula. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Maecenas sollicitudin.

Nulla pulvinar eleifend sem. Aenean vel massa quis mauris vehicula lacinia. Aenean placerat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed ac dolor sit amet purus malesuada congue. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Vivamus porttitor turpis ac leo. Nam quis nulla. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Maecenas aliquet accumsan leo.

Aliquam in lorem sit amet leo accumsan lacinia. Mauris metus. Cras elementum. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Sed convallis magna eu sem. Phasellus faucibus molestie nisl. Nunc auctor. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Fusce tellus. Etiam posuere lacus quis dolor. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam bibendum elit eget erat. Nunc dapibus tortor vel mi dapibus sollicitudin. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus.

Etiam commodo dui eget wisi. Integer pellentesque quam vel velit. Aliquam ante. Aliquam ornare wisi eu metus. Mauris elementum mauris vitae tortor. Maecenas libero. Phasellus faucibus molestie nisl. Nullam faucibus mi quis velit. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Curabitur vitae diam non enim vestibulum interdum. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Donec quis nibh at felis congue commodo. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Nullam sapien sem, ornare ac, nonummy non, lobortis a enim.

Fusce nibh. Quisque tincidunt scelerisque libero. Mauris tincidunt sem sed arcu. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Fusce suscipit libero eget elit. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Etiam commodo dui eget wisi. Maecenas libero. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Nunc dapibus tortor vel mi dapibus sollicitudin.

Nullam faucibus mi quis velit. Duis viverra diam non justo. Cras elementum. Nam sed tellus id magna elementum tincidunt. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Integer lacinia. Fusce nibh. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec vitae arcu. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Nulla non lectus sed nisl molestie malesuada. Praesent id justo in neque elementum ultrices. Morbi leo mi, nonummy eget tristique non, rhoncus non leo. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Aenean placerat. Fusce nibh. Mauris dictum facilisis augue.

Etiam bibendum elit eget erat. Ut tempus purus at lorem. Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Etiam posuere lacus quis dolor. Nullam faucibus mi quis velit. Fusce tellus odio, dapibus id fermentum quis, suscipit id erat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec quis nibh at felis congue commodo. Suspendisse sagittis ultrices augue.

Aliquam erat volutpat. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Donec quis nibh at felis congue commodo. Duis viverra diam non justo. Integer imperdiet lectus quis justo. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Maecenas fermentum, sem in pharetra pellentesque, velit turpis volutpat ante, in pharetra metus odio a lectus. Mauris metus. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Fusce aliquam vestibulum ipsum. Vestibulum fermentum tortor id mi. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Duis condimentum augue id magna semper rutrum. Integer vulputate sem a nibh rutrum consequat. Fusce suscipit libero eget elit. Nam sed tellus id magna elementum tincidunt.

Duis bibendum, lectus ut viverra rhoncus, dolor nunc faucibus libero, eget facilisis enim ipsum id lacus. Pellentesque sapien. Duis sapien nunc, commodo et, interdum suscipit, sollicitudin et, dolor. Fusce suscipit libero eget elit. Nulla est. Etiam sapien elit, consequat eget, tristique non, venenatis quis, ante. Mauris metus. Aliquam ornare wisi eu metus. Aliquam erat volutpat. Fusce tellus. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem.

Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Praesent in mauris eu tortor porttitor accumsan. Cras elementum. Proin mattis lacinia justo. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus et lorem id felis nonummy placerat. Donec iaculis gravida nulla. Sed ac dolor sit amet purus malesuada congue. Sed convallis magna eu sem. Mauris dictum facilisis augue. Sed vel lectus. Donec odio tempus molestie, porttitor ut, iaculis quis, sem. Fusce consectetuer risus a nunc. Integer tempor. Sed ac dolor sit amet purus malesuada congue. Aliquam ornare wisi eu metus. Etiam posuere lacus quis dolor.

Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Integer in sapien. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Mauris tincidunt sem sed arcu. Aliquam erat volutpat. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Mauris dictum facilisis augue. In enim a arcu imperdiet malesuada. Duis viverra diam non justo. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Nulla non lectus sed nisl molestie malesuada. Donec vitae arcu. Pellentesque sapien. Praesent in mauris eu tortor porttitor accumsan. In enim a arcu imperdiet malesuada.

Vestibulum fermentum tortor id mi. Etiam commodo dui eget wisi. Mauris dictum facilisis augue. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Nunc auctor. Proin in tellus sit amet nibh dignissim sagittis. Aliquam id dolor. Curabitur vitae diam non enim vestibulum interdum. Aliquam erat volutpat. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo.

Curabitur sagittis hendrerit ante. Et harum quidem rerum facilis est et expedita distinctio. Quisque tincidunt scelerisque libero. Sed convallis magna eu sem. Aliquam erat volutpat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Etiam commodo dui eget wisi. Fusce aliquam vestibulum ipsum. Etiam dui sem, fermentum vitae, sagittis id, malesuada in, quam. Nulla quis diam.

Nulla non arcu lacinia neque faucibus fringilla. Nullam rhoncus aliquam metus. Fusce consectetuer risus a nunc. Pellentesque sapien. Etiam quis quam. Vivamus porttitor turpis ac leo. Integer pellentesque quam vel velit. Suspendisse sagittis ultrices augue. Integer pellentesque quam vel velit. Nullam rhoncus aliquam metus.

Et harum quidem rerum facilis est et expedita distinctio. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Integer malesuada. Nulla non lectus sed nisl molestie malesuada. Integer vulputate sem a nibh rutrum consequat. Quisque tincidunt scelerisque libero. Curabitur sagittis hendrerit ante. Nunc tincidunt ante vitae massa. Nulla non lectus sed nisl molestie malesuada. Nunc auctor. Nullam sit amet magna in magna gravida vehicula. Vivamus luctus egestas leo. Nullam faucibus mi quis velit. Vivamus ac leo pretium faucibus. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus.','2018-08-20 15:58:20',1,5);
